base: /
languages:
  -
    title: English
    enabled: true
    locale: en-US
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: ''
    flag: global
    languageId: 0
rootPageId: 3
websiteTitle: Portfolio
